# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: offers.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'offers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coffers.proto\"\x1d\n\x0cOfferRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"@\n\x05Offer\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"\'\n\rOfferResponse\x12\x16\n\x06offers\x18\x01 \x03(\x0b\x32\x06.Offer2:\n\x0cOfferService\x12*\n\tGetOffers\x12\r.OfferRequest\x1a\x0e.OfferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'offers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFFERREQUEST']._serialized_start=16
  _globals['_OFFERREQUEST']._serialized_end=45
  _globals['_OFFER']._serialized_start=47
  _globals['_OFFER']._serialized_end=111
  _globals['_OFFERRESPONSE']._serialized_start=113
  _globals['_OFFERRESPONSE']._serialized_end=152
  _globals['_OFFERSERVICE']._serialized_start=154
  _globals['_OFFERSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
